### ISSUE TITLE
Publish To Maven Central

### ISSUE THREAD

**Issue by opticyclic** [lightszentip/logmanagement-plugin#1]
My company wont let me use non-standard maven repositories.
Can you publish to Maven Central please.

**Comment by lightszentip** [comment]
I will try to publish the artifact to maven central.

**Comment by lightszentip** [comment]
You can find the artifact

<dependency>
  <groupId>com.lightszentip.module</groupId>
  <artifactId>logmanagement-plugin</artifactId>
  <version>0.9.1</version>
</dependency>

https://oss.sonatype.org/#nexus-search;quick~lightszentip

And I hope it will sync with maven central.

**Comment by lightszentip** [comment]
@opticyclic now you find the artifact under http://repo1.maven.org/maven2/com/lightszentip/module/logmanagement-plugin/
